CREATE TABLE [dbo].[Tournaments]
(
	[Id]              BIGINT IDENTITY (1, 1) NOT NULL,
	[Name]            NVARCHAR(256) NOT NULL,
	[StartDate]       DATETIMEOFFSET NOT NULL,
	[EndDate]   	  DATETIMEOFFSET NOT NULL,
	[CreatedAtUtc]    DATETIME2 NOT NULL DEFAULT GETUTCDATE(),

	CONSTRAINT [PK_Tournaments] PRIMARY KEY CLUSTERED ([Id] ASC)
)